#!/bin/sh

ROOT="$(git root)"
LABELS="$@"

rm -f "$ROOT/README.md"

exec 3>&1 1>"$ROOT/README.md"
cat $ROOT/.readme/0*.md
for label in $LABELS
do
    git check "$label"
done
exec 1>&3

chmod -w "$ROOT/README.md"

git add "$ROOT/README.md"
git commit -m "Update README.md"

