#!/bin/sh

# Get the repository root path.
ROOT="$(git root)"

rm -f "$ROOT/README.md"

# Save and redirect 'stdout' to 'README.md'.
exec 3>&1 1>"$ROOT/README.md"

# Concatenate all MarkDown files that start with '0'.
cat $ROOT/meta/0*.md

# Run repository checks.
git check "TODO"
git check "IDEA"

# Restore 'stdout'.
exec 1>&3

# Make 'README.md' file read-only.
chmod -w "$ROOT/README.md"

# Commit 'README.md' file.
git add "$ROOT/README.md"
git commit -m "README.md"

