#!/bin/sh

# Run repository checks.
git check "TODO"
git check "IDEA"

# Get the repository root path.
ROOT="$(git root)"
FILENAME="README.md"
FILE="$ROOT/$FILENAME"
META="$ROOT/meta"

# Remove old 'README.md' file.
rm -rf $FILE

# Create new 'README.md' file.
touch $FILE

# Save and redirect 'stdout' to 'README.md' file.
exec 3>&1 1>"$FILE"

# Write 'DESCRIPTION' if exists.
[ -f $META/INDEX.md ] \
    && cat $META/INDEX.md

# Write 'SETUP.md' if exists.
[ -f $META/SETUP.md ] \
    && cat $META/SETUP.md

# Write 'USAGE.md' if exists.
[ -f $META/USAGE.md ] \
    && cat $META/USAGE.md

# Write 'ARCHITECTURE.md' if exists.
[ -f $META/ARCHITECTURE.md ] \
    && cat $META/ARCHITECTURE.md

# Write 'REPORT.md' if exists.
[ -f $META/TODO.md ] \
    && cat $META/TODO.md

# Write 'REPORT.md' if exists.
[ -f $META/IDEA.md ] \
    && cat $META/IDEA.md

# Make 'README.md' file read-only.
chmod -w $FILE

# Restore 'stdout'.
exec 1>&3

# Commit 'README.md' file.
git add "$FILE"
git commit -m "$FILENAME"

