#!/bin/sh

# shell
alias e="exit"
alias c="clear && l"
alias o="xdg-open"
alias v="nvim"
alias t="touch"
alias md="mkdir"
alias cm="chmod"

# ls: Show hidden files by default.
alias ls="ls -a"

# cd: Navigate quickly.
alias d="cd"
alias ..="cd .."
alias ...="cd ../.."

# scripts
alias a="append"
alias u="source update"

# exa: Use as default list tool.
alias l="exa"
alias la="exa -a"
alias ll="exa -l"
alias lla="exa -la"

# tmux: Use UTF-8 in tmux.
alias tmux="tmux -u"

# git: Use lots of shortcuts.
alias g="git"
alias ga="git add"
alias gc="git commit"
alias gi="git issues"
alias gs="git status"
alias gu="git update"
alias grm="git remove"
alias gmv="git rename"

# home: Manage $HOME files with a bare Git repository.
alias home="git --git-dir=$HOME/.home.git --work-tree=$HOME"
alias h="home"
alias ha="home add"
alias hc="home commit"
alias hi="home issues"
alias hs="home status"
alias hu="home update"
alias hrm="home remove"
alias hmv="home rename"

