#!/bin/sh

# shell
alias e="exit"
alias c="clear && l"
alias o="xdg-open"
alias v="nvim"
alias md="mkdir"
alias cm="chmod"
alias sw="source workspace"

# ls: Show hidden files by default.
alias ls="ls -a"

# cd: Navigate quickly.
alias d="cd"
alias ..="cd .."
alias ...="cd ../.."

# xclip
alias copy="xclip"
alias paste="xclip -o"

# bat
alias bat="batcat"

# scripts
alias a="append"
alias u="source update"

# exa: Use as default list tool.
alias l="exa"
alias la="exa -a"
alias ll="exa -l"
alias lla="exa -la"

# tmux: Use UTF-8 in tmux.
alias tmux="tmux -u"

# git: Use lots of shortcuts.
alias g="git"
alias ga="git add"
alias gb="git build"
alias gc="git commit"
alias gd="git diff"
alias gi="git ignore"
alias gl="git log"
alias gr="git report"
alias gs="git status"
alias gt="git todo"
alias gu="git update"
alias grm="git remove"
alias gmv="git rename"

# home: Manage $HOME files with a bare Git repository.
alias home="git --git-dir=$HOME/.home.git --work-tree=$HOME"
alias h="home"
alias ha="home add"
alias hb="home build"
alias hc="home commit"
alias hd="home diff"
alias hi="home ignore"
alias hl="home log"
alias hr="home report"
alias hs="home status"
alias ht="home todo"
alias hu="home update"
alias hrm="home remove"
alias hmv="home rename"

# todo.txt
alias t="todo-txt -d $HOME/.config/todo-txt/todo.cfg"
alias at="append $TODO_FILE"
alias ot="$EDITOR $TODO_FILE"

# notes
alias an="append $NOTES/$(date +%Y-%m-%d) $(date +%H:%M)"
alias on="$EDITOR "$NOTES""

