format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$time\
$status\
$shell\
$character"""

add_newline = false

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "


