#!/usr/bin/env bash

# Use bash strict mode.
set -Eeuo pipefail

# Check for / define '$LABELS'.
[[ ! -v "LABELS" ]] && LABELS='TODO|FIXME|BUG|NOTE|XXX|HACK|FEATURE|IDEA|WISH'

# Define names of tmp files. 
TMP_ISSUES=".issues.tmp"
TMP_IGNORE=".issuesignore.tmp"
TMP_FILES=".issuefiles.tmp"

# Get the root path of the repository.
root=$(git rev-parse --show-toplevel)

# Define the regex source and replace patterns.
# IDEA: Add support for `--ignore-issue` comments for lines to ignore.
ESCAPED_LABELS=$(echo "$LABELS" | sed 's/|/\\|/g')
SOURCE_PATTERN='HEAD:\([^:]*\):\([0-9]*\):.*\('"$ESCAPED_LABELS"'\): \(.*\)'
REPLACE_PATTERN='- [ ] [`#L\2`](\1#L\2) **`\3`** \4'

# Save .issueignore if exists.
if [[ -f "$root/.issuesignore" ]]
then
    # Remove comments from the .issueignore file and save it in a tmp file. 
    git grep "^[^#]" HEAD -- "$root/.issuesignore" \
        | sed 's/^HEAD:.issuesignore://' \
        > "$root/$TMP_IGNORE" \
        || true

    git ls-files \
        | grep -v -E -f "$root/$TMP_IGNORE" \
        > "$root/$TMP_FILES" \
        || true
else
    git ls-files > "$root/$TMP_FILES"
fi

# Loop over all files tracked in the repository that are not ignored.
for file in $(cat "$root/$TMP_FILES")
do
    # Extract all lines of the file at HEAD, that have one of the defined issue labels.
    git grep -n -E '('"$LABELS"'): ' "HEAD" -- "$root/$file" \
        > "$root/$TMP_ISSUES" \
        || true

    # Continue with the next file, if no lines where extracted.
    if [[ ! -s "$root/$TMP_ISSUES" ]]
    then
        continue
    fi
    
    # Write the subheading for the current file.
    echo "## [$file]($file)"
    echo ""

    # Transform and write the raw lines in Markdown.
    cat "$root/$TMP_ISSUES" | sed 's/'"$SOURCE_PATTERN"'/'"$REPLACE_PATTERN"'/'
    
    # Write a newline as a spacer for the next section.
    echo ""
done

# Clean-up the tmp files.
rm -f "$root/$TMP_ISSUES" "$root/$TMP_IGNORE" "$root/$TMP_FILES"

