#!/bin/sh

# Update installed packages.
sudo apt update && sudo apt upgrade

# Make scripts executable.
for script in $SCRIPTS
do
    chmod +x "$script"
done

# Update the shell environment.
source .zshrc

# Build home repository.
home build

